config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :shops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def delete
    Shop.find(params[:id]).destroy
  end

  def create
    @shop = Shop.new(shops_params)
 
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end
 
  def update
    @shop = Shop.find(params[:id])
  
    if @shop.update(shops_params)
      redirect_to shops_path
    else
      render :edit
    end
  end

  private
 
    def shops_params
      params.require(:shop).permit(:name, :desc, :ranking, :is_deleted)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar">
<h4> <%= link_to 'Home', root_path %> </h4>
<h4> <%= link_to 'About', about_path %> </h4>
<h4> <%= link_to 'Restaurants', shops_path %> </h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopblocker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Shadows+Into+Light|Unica+One" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shops/delete.html.erb
<h1>Shops#delete</h1>
<p>Find me in app/views/shops/delete.html.erb</p>

app/views/shops/edit.html.erb
<h1>Edit</h2>
<%= form_for @shop do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :desc %>
  <%= f.text_field :desc %>

  <%= f.label :ranking %>
  <%= f.text_area :ranking %>

  <%= f.submit %>
<% end %>

app/views/shops/index.html.erb
<div class="toptitle">
<h1>Main Restaurant List</h1><p class="createnew"><%= link_to 'Create New', new_shop_path %></p>
</div>
<div class="biglist">
<% @shops.each do |shop| %>
  <div class="listitem">
  <h3 class="shopname"><%= shop.name %></h3>
  <h3><%= link_to 'Show', shop_path(shop) %></h3>
  <h3><%= link_to 'Edit', edit_shop_path(shop) %></h3>
  <h3><%= link_to 'Delete', shop, method: :delete %></h3>
  </div>
<% end %>
</div>

app/views/shops/new.html.erb
<h1>Submit a New Restaurant</h1>
<%= form_for @shop do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :desc %>
  <%= f.text_field :desc %>

  <%= f.label :ranking %>
  <%= f.text_area :ranking %>

  <%= f.submit %>
<% end %>

app/views/shops/show.html.erb
<h1>Restaurant Details</h1>
<div class="show">
  <h3><strong>Name: </strong><%= @shop.name %></h3>
  <h3><strong>Description: </strong><%= @shop.desc %></h3>
  <h3><strong>Customer ranking: </strong><%= @shop.ranking.to_s %></h3>
</div>

app/views/static_pages/about.html.erb
<h1>About Me</h1>
<p class="about">
I was born in a cross-fire hurricane
And I howled at the morning driving rain
But it's all right now, in fact, it's a gas
But it's all right. I'm Jumpin' Jack Flash
It's a gas, gas, gas
I was raised by a toothless, bearded hag,
I was schooled with a strap right across my back
But it's all right now, in fact, it's a gas
But it's all right, I'm Jumpin' Jack Flash
It's a gas, gas, gas
I was drowned, I was washed up and left for dead
I fell down to my feet and I saw they bled , yeah yeah
I frowned at the crumbs of a crust of bread
Yeah, yeah, yeah
I was crowned with a spike right through my head
But it's all right now, in fact, it's a gas
But it's all right, I'm Jumpin' Jack Flash
It's a gas, gas, gas.
</p>

app/views/static_pages/home.html.erb
<div class="home">
<h1>Shopblocker</h1>
<p class="aside">The best restaurant app you've never heard of.</p>
</div>